# Generated by Django 5.0.14 on 2025-08-30 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=160)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(blank=True, max_length=40)),
                ('assunto', models.CharField(blank=True, max_length=200)),
                ('mensagem', models.TextField()),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('lido', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=160)),
                ('slug', models.SlugField(blank=True, max_length=160, unique=True)),
                ('descricao', models.TextField(blank=True)),
                ('imagem_capa', models.ImageField(blank=True, null=True, upload_to='portfolio/')),
                ('cliente', models.CharField(blank=True, max_length=160)),
                ('data_obra', models.DateField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('ordem', models.IntegerField(default=0)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=160)),
                ('slug', models.SlugField(blank=True, max_length=160, unique=True)),
                ('resumo', models.CharField(blank=True, max_length=255)),
                ('descricao', models.TextField(blank=True)),
                ('imagem_capa', models.ImageField(blank=True, null=True, upload_to='servicos/')),
                ('ordem', models.IntegerField(default=0)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('chave', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('valor', models.TextField()),
            ],
        ),
    ]
