# Generated by Django 5.0.14 on 2025-08-31 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_rafael', '0002_banner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner',
            options={'ordering': ['-id']},
        ),
        migrations.RenameField(
            model_name='banner',
            old_name='ativo',
            new_name='b_sit',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='imagem',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='ordem',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='titulo',
        ),
        migrations.AddField(
            model_name='banner',
            name='b_subtitulo',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='banner',
            name='b_tipo',
            field=models.CharField(choices=[('desktop', 'Desktop'), ('mobile', 'Mobile')], db_index=True, default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='banner',
            name='b_titulo',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='banner',
            name='proj_hash',
            field=models.CharField(db_index=True, default='', max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='banner',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterModelTable(
            name='banner',
            table='tbl_banners_',
        ),
    ]
