# Generated by Django 5.0.14 on 2025-08-31 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_rafael', '0003_alter_banner_options_rename_ativo_banner_b_sit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='imagem',
            field=models.ImageField(default='', upload_to='banners/'),
            preserve_default=False,
        ),
    ]
