# Generated by Django 5.0.14 on 2025-08-31 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_rafael', '0004_banner_imagem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner',
            options={'ordering': ['-id'], 'verbose_name': 'Banner', 'verbose_name_plural': 'Banners'},
        ),
        migrations.RemoveField(
            model_name='banner',
            name='b_sit',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='b_subtitulo',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='b_tipo',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='b_titulo',
        ),
        migrations.AddField(
            model_name='banner',
            name='ativo',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.AddField(
            model_name='banner',
            name='subtitulo',
            field=models.CharField(blank=True, max_length=200, verbose_name='Subtítulo'),
        ),
        migrations.AddField(
            model_name='banner',
            name='titulo',
            field=models.CharField(blank=True, max_length=200, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True, verbose_name='Atualizado em'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='imagem',
            field=models.ImageField(upload_to='banners/', verbose_name='Imagem'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='proj_hash',
            field=models.CharField(db_index=True, max_length=64, verbose_name='Projeto'),
        ),
    ]
