# Generated by Django 5.0.14 on 2025-08-31 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_rafael', '0005_alter_banner_options_remove_banner_b_sit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='proj_hash',
        ),
    ]
