# Generated by Django 5.0.14 on 2025-08-31 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_rafael', '0006_remove_banner_proj_hash'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='subtitulo',
        ),
    ]
