# Generated by Django 5.0.14 on 2025-09-02 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_rafael', '0007_remove_banner_subtitulo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atuacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('p_desc', models.TextField(blank=True, verbose_name='Descrição')),
                ('p_sit', models.BooleanField(default=True, verbose_name='Ativo')),
                ('ordem', models.IntegerField(db_index=True, default=0, verbose_name='Ordem')),
                ('slug', models.SlugField(blank=True, max_length=220, verbose_name='Slug')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Atuação',
                'verbose_name_plural': 'Atuações',
                'db_table': 'tbl_paginas_',
                'ordering': ['ordem', 'id'],
            },
        ),
    ]
