# Generated by Django 5.0.14 on 2025-09-02 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_rafael', '0008_atuacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='atuacao',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='atuacoes/', verbose_name='Imagem'),
        ),
        migrations.AddField(
            model_name='atuacao',
            name='p_resumo',
            field=models.CharField(blank=True, max_length=255, verbose_name='Resumo'),
        ),
    ]
