# Generated by Django 5.0.14 on 2025-09-03 10:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_rafael', '0009_atuacao_imagem_atuacao_p_resumo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contato',
            options={'ordering': ['-id']},
        ),
        migrations.RemoveField(
            model_name='contato',
            name='assunto',
        ),
        migrations.RemoveField(
            model_name='contato',
            name='criado_em',
        ),
        migrations.RemoveField(
            model_name='contato',
            name='email',
        ),
        migrations.RemoveField(
            model_name='contato',
            name='ip',
        ),
        migrations.RemoveField(
            model_name='contato',
            name='lido',
        ),
        migrations.RemoveField(
            model_name='contato',
            name='mensagem',
        ),
        migrations.RemoveField(
            model_name='contato',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='contato',
            name='telefone',
        ),
        migrations.RemoveField(
            model_name='contato',
            name='user_agent',
        ),
        migrations.AddField(
            model_name='contato',
            name='c_cidade',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Cidade'),
        ),
        migrations.AddField(
            model_name='contato',
            name='c_dc',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Data'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contato',
            name='c_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='E-mail'),
        ),
        migrations.AddField(
            model_name='contato',
            name='c_mensagem',
            field=models.TextField(default='', verbose_name='Mensagem'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contato',
            name='c_nome',
            field=models.CharField(default=1, max_length=160, verbose_name='Nome'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contato',
            name='c_origem',
            field=models.CharField(default='2', max_length=10, verbose_name='Origem'),
        ),
        migrations.AddField(
            model_name='contato',
            name='c_telefone',
            field=models.CharField(blank=True, max_length=40, verbose_name='Telefone'),
        ),
        migrations.AlterModelTable(
            name='contato',
            table='tbl_contatos_',
        ),
    ]
